services:
  db:
    image: postgres:15-alpine
    container_name: audigest_db
    restart: always
    environment:
      POSTGRES_USER: audigest_user     
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: audigest_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: audigest_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: